version: '3.8'

services:
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0'"
    volumes:
      - .:/app
    environment:
      - REDIS_URL=redis://redis:6379/0
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    depends_on:
      - redis

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  
  worker:
    build: .
    command: bundle exec rake resque:work QUEUE=*
    volumes:
      - .:/app
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis